import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';
import { Navbar } from '@/components/Navbar';
import Link from 'next/link';
import { MessageSquareText, Moon } from 'lucide-react';
import { ButtonMotion } from '@/components/ButtonMotion';
import { NavLink } from '@/components/Navlink';
import { Aside } from '@/components/Aside';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-base-light`}>
        <Aside
          firstname={'Eduardo'}
          lastname={'Pacheco'}
          specialization={'Dev. Full-Stack'}
          basedIn={'Pará, Brasil'}
        />
        <Navbar
          brand={
            <Link href="/" className="text-gradient font-bold text-3xl ">
              EAP Projetos
            </Link>
          }
          rightButton={
            <>
              <button className="hidden xl:block p-2 text-t-disabled-light group cursor-pointer">
                <Moon className="group-hover:text-t-bright-light" />
              </button>
              <ButtonMotion>
                <span>Vamos Conversa</span>
                <MessageSquareText />
              </ButtonMotion>
            </>
          }
        >
          <NavLink isActive>Início</NavLink>
          <NavLink>Portfólio</NavLink>
          <NavLink>Sobre Mim</NavLink>
          <NavLink>Currículo</NavLink>
          <NavLink>Contato</NavLink>
        </Navbar>

        <div className="max-w-10/12 ml-auto mt-32 px-8">{children}</div>
      </body>
    </html>
  );
}
