import type { Metadata } from 'next';
import './globals.css';
import { ReactNode } from 'react';
import Link from 'next/link';
import { MessageSquareText, Moon } from 'lucide-react';
import { Navlink } from '@/components/Navbar/navlink';
import { Button } from '@/components/ui/button';
import { Navbar } from '@/components/Navbar';
import { AsideAvatar } from '@/components/AsideAvatar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased bg-base-light relative`}>
        <AsideAvatar
          firstname={'Eduardo'}
          lastname={'Pacheco'}
          specialization={'Dev. Full-Stack'}
          basedIn={'Pará, Brasil'}
        />
        <Navbar
          brand={
            <Link href="/#" className="text-gradient font-bold text-2xl md:text-3xl ">
              EAP Projetos
            </Link>
          }
          rightButton={
            <>
              <Button variant={'glass'} size={'default'} className="">
                <Moon className="group-hover:text-t-bright-light" />
              </Button>
              <Button
                variant={'primary'}
                icon={<MessageSquareText />}
                iconPosition={'right'}
                size={'medium'}
              >
                Vamos Conversa
              </Button>
            </>
          }
        >
          <Navlink href={'/#inicio'} isActive>
            Início
          </Navlink>
          <Navlink href={'/#portfolio'}>Portfólio</Navlink>
          <Navlink href={'/#sobre-mim'} className={'lg:hidden 2xl:block'}>
            Sobre Mim
          </Navlink>
          <Navlink href={'/#curriculo'}>Currículo</Navlink>
          <Navlink href={'/#contato'}>Contato</Navlink>
        </Navbar>

        <div className="px-2 w-full lg:w-8/12 lg:mr-4 ml-auto 2xl:mr-auto xl:px-8 xl:mr-8 2xl:w-auto 2xl:ml-[420px]">
          {children}
        </div>
      </body>
    </html>
  );
}
